OnlineGCA/OnlineGCA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('', include('food.urls')),
    path('users/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout')
]

OnlineGCA/food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('', views.TestItem, name = 'TestItemView'),
    path('home/', views.TestHomeView, name = 'TestHomeView'),
    path('food/', views.TestItem, name = 'TestItemView'),
    path('<int:item_id>/', views.TestDetailView, name = 'TestItemDetails'),
    path('addItem/', views.TestAddItem, name= 'AddItem'),
    path('updateItem/<int:item_id>/', views.TestUpdateItem, name= 'UpdateItem'),
    path('delete/<int:item_id>/', views.DeleteItem, name= 'DeleteItem')
]

OnlineGCA/users/urls.py
from . import views
from django.urls import path

app_name = 'users'
urlpatterns = [
    path('createUser/', views.CreateUser, name= "CreateUser"),
    path('profile/', views.ProfilePage, name= 'ProfilePage')
]

OnlineGCA/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Food(models.Model):
    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete= models.CASCADE, default= 1)
    item_name = models.CharField(max_length= 240)
    item_description = models.CharField(max_length= 240)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length= 1_000, default = 'https://cdn.dribbble.com/users/1012566/screenshots/4187820/media/985748436085f06bb2bd63686ff491a5.jpg?compress=1&resize=400x300&vertical=top')

    def get_absolute_url(self):
        return reverse('food:TestItemDetails', kwargs={'pk': self.pk})

OnlineGCA/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    image = models.ImageField(default= 'profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=500)
    def __str__(self):
        return self.user.username
    

OnlineGCA/food/forms.py
from django import forms
from .models import Food

class ItemForm(forms.ModelForm):
    class Meta:
        model= Food
        fields= ['item_name', 'item_description', 'item_price', 'item_image']

OnlineGCA/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

OnlineGCA/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Food
from .forms import ItemForm
from django.template import loader
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# Create your views here.
def TestHomeView(request):
    return HttpResponse('Hello World')

def TestItem(request):
    items = Food.objects.all()
    template = loader.get_template('food/TestItem.html')
    context = {
        'item_list': items,
    }
    return HttpResponse(template.render(context, request))

def TestDetailView(request, item_id): 
    item = Food.objects.get(pk = item_id)
    context = {
            'item': item,
    }
    return render(request, 'food/TestDetail.html', context)

def TestAddItem(request):
    form = ItemForm(request.POST or None)
    if form.is_valid(form):
        form.instance.username = request.user
        form.save()
        return redirect('food:TestItemView')
    return render(request,'food/AddItem.html', {'form':form})

def TestUpdateItem(request, item_id):
    item = Food.objects.get(id = item_id)
    form = ItemForm(request.POST or None, instance= item)
    if form.is_valid():
        form.save()
        return redirect('food:TestItemView')
    return render(request, 'food/AddItem.html', {'form':form, 'item': item})

def DeleteItem(request, item_id):
    item = Food.objects.get(id = item_id)
    if request.method == 'POST':
        item.delete()
        return redirect('food:TestItemView')
    return render(request, 'food/DeleteConfirmation.html', {'item': item})

OnlineGCA/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def CreateUser(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Username created sucessfully!')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/CreateUser.html', {'form': form})

@login_required
def ProfilePage(request):
    return render(request, 'users/ProfilePage.html')

OnlineGCA/food/templates/food/AddItem.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}    
    {{ form }}
    <button type="submit">Save Item</button>
</form>
{% endblock %}

OnlineGCA/food/templates/food/DeleteConfirmation.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you shure you want to delete {{item.item_name}}?</h1>
    <button type="submit">Delete Item</button>
</form>

OnlineGCA/food/templates/food/TestDetail.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{item.item_image}}" class="card" heigh="300px" />
        </div>
        <div class="col-md-6">
            <h1>{{item.item_name}}</h1>
            <h2>{{item.item_description}}</h2>
            <h3>Price: R${{item.item_price}}</h3>
            <a href="{% url 'food:DeleteItem' item.id %}">Delete Item</a>
        </div>
    </div>
</div>
{% endblock %}

OnlineGCA/food/templates/food/TestItem.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</head>
<body>
    {% block body%}
    {%for item in item_list %}
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="card" height="150px" src="{{item.item_image}}"/>
        </div>
        <div class="col-md-4">
            <li>
                <a href="{% url 'food:TestItemDetails' item.id %}">
                    <h1>{{item.item_name}}</h1>
                </a>
            </li>
            <h5>{{item.item_description}}</h5>   
            <h6>{{item.item_price}}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:TestItemDetails' item.id %}" class="btn btn-success">Ver Detalhes</a>
        </div>
    </div>
    {% endfor %}
    {% endblock %}
</body>
</html>

OnlineGCA/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark" widht="100%">
        <a href="{% url 'food:TestItemView' %}" class="navbar-brand">FoodApp</a>
        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'food:AddItem' %}">Add Item</a>
            <a class="nav-item nav-link" href="#">View Item</a>
            <a class="nav-item nav-link" href="#">Delete Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'users:ProfilePage' %}">{{user.username}}</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tag}}">{{message}}</div>
        {% endfor %}
    {% endif%}
    {% block body %}
    {% endblock %}
</body>
</html>

OnlineGCA/users/templates/users/CreateUser.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Sign Up</button>
</form>

OnlineGCA/users/templates/users/ProfilePage.html
{% extends 'food/base.html' %}

{% block body %}
<h1>User Profile</h1>
<h2>{{user.username}}</h2>
{% endblock %}

OnlineGCA/users/templates/users/login.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
    <br>
    {%csrf_token%}
    {{ form }}
    <button type="submit">Login</button>
    </br>
</form>
{% endblock %}

OnlineGCA/users/templates/users/logout.html
<h2>You have been logged out!</h2>